name: Sonar Fallback for Forked PRs

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  sonar_from_fork:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests[0].head.repo.full_name != github.event.workflow_run.repository.full_name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR source
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: sonar

      - name: Run Sonar analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
              -Dsonar.organization=woped
              -Dsonar.projectKey=woped_${{ github.event.repository.name }}
              -Dsonar.host.url=https://sonarcloud.io
              -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }}
              -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }}
              -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }}
